/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("it.unicam.cs.pa.java-application-conventions")
    id("org.openjfx.javafxplugin") version "0.1.+"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":lib"))
}

javafx {
    version = "21"
    modules("javafx.controls", "javafx.fxml")
}

application {
    // Define the main class for the application.
    mainClass.set("it.unicam.cs.pa.app.App")
    mainModule.set("it.unicam.cs.pa.app")
}
