/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("it.unicam.cs.pa.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":lib"))
}

application {
    // Define the main class for the application.
    mainClass.set("it.unicam.cs.pa.app.App")
}
