/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.app;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

import java.util.Objects;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        FXMLLoader fxmlLoader = new FXMLLoader(Objects.requireNonNull(getClass().getResource("simulator.fxml")));
        stage.setScene(new Scene(fxmlLoader.load()));
        stage.setTitle("RobotSwarm");
        stage.setResizable(false);
        stage.getIcons().add(new Image(Objects.requireNonNull(getClass().getResourceAsStream("robotSwarm.jpg"))));

        stage.show();
    }
}
